/**
 * Follow-up Types and Status Enums
 */
const FOLLOWUP_TYPES = {
  CONSULTATION: 'CONSULTATION',
  MEDICATION_REVIEW: 'MEDICATION_REVIEW',
  VACCINATION: 'VACCINATION',
  REFERRAL: 'REFERRAL',
  GENERAL: 'GENERAL'
};

const FOLLOWUP_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  MISSED: 'MISSED',
  CANCELLED: 'CANCELLED',
  OVERDUE: 'OVERDUE' // Dynamic status for reporting/responses
};

const ALLOWED_FOLLOWUP_TYPES = Object.values(FOLLOWUP_TYPES);
const ALLOWED_PERSISTED_FOLLOWUP_STATUSES = [
  FOLLOWUP_STATUS.PENDING,
  FOLLOWUP_STATUS.COMPLETED,
  FOLLOWUP_STATUS.MISSED,
  FOLLOWUP_STATUS.CANCELLED
];

module.exports = {
  FOLLOWUP_TYPES,
  FOLLOWUP_STATUS,
  ALLOWED_FOLLOWUP_TYPES,
  ALLOWED_PERSISTED_FOLLOWUP_STATUSES
};
